@Restaurants.API_HostAddress = https://localhost:7112
@token = CfDJ8MsiFju5D8dEhQLF9cu1mcoT_fQHmHX4hKSTCQGW1MiCcUthGeFyXb8xojNH_xG8jxdBT7Bq6l4jJ1aQd5j8iTBbAhVIDUxBXkrfsccgMTEBean2403ZiI2oRyZpO2fMwPEd15BxRouwn25XIjhPiNjt9ujZhRqFvHtYv2zOZE9QOBAQx2AjvpmjifPE5sYvDKXi8NPzHO1lCvt0yfKtxtHyKMwtNq1aXLQCX4zESyQgLN0s0mn7y1OBqXLwusuMM5d2Ni3MfaLJHLv-4STNdGnGPW3dZiub3IGPQlOfap7X3du9kOrlT4piGMmhk7UFmvGrb6j3zTAogodRJA9v2w-v7enQrr_oqSESf1rAWa-Nb0UiY5PJFn-0i0AKF2UMIdZxafdTH5Cfkpoixv1eb7uvn6d3JILS3hfU54x4Hbk5h-YXLxKl7Cp-sTwzFEau2U_A6FbkQAbCRT7zL5piARUzfngU8zoaW31O2eosZ0fxUxRD6wMz6FYM1c7B1P-lUaijvLYbzTtHuCDakSs1u5NI3v9LxNFHUbSnJY6FRB3tUy8WzuM2QRp_OfnWQ74h9l-S6RZfqVM5B4nf2Ctat8klT4IGhH_32FqRZHp6M6t5u59KR37Q5T2BQP_OO_BKg7bCYKJ5pppNCVCxWHJ_TtMbkvf9m9zNBV8QzFs3HnYOgxggEAsuQVWT9ChnfF7TZnXNC19XNeJANi3XN2JapG1HE-hTNCMxEUEXxHoynJaoIRfr2Gb4OH6ngXBe_lJWksGopnT7mcGkMrokh4CvjWM9xYGUbu5-YEPPB4wO4thG

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
#Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/16
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Pukka Pizzas",
  "Description": "Funky Pizzas",
  "Category": "Italian",
  "ContactEmail": "info@funkypizzas.com",
  "ContactNumber": "04745 445 4",
  "PostalCode":"12457-444",
  "City": "Paris",
  "Street": "Rue de la Paix",
  "HasDelivery": true
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/14
Authorization: Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/14
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Pukka Pizza",
  "Description": "funky pizza restaurant",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes
Content-Type: application/json

{
 "Name": "Chicken Biriyani",
 "Description": "A delicious dish made with basmati rice, chicken and a variety of spices",
 "Price": 13.50,
 "KiloCalories": 850
}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes/18
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes
Authorization: Bearer {{token}}
###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "owner2@test.com",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner2@test.com",
  "password": "Password1!"
}
###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "DateOfBirth": "2010-01-01",
  "Nationality": "British"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "UserEmail": "owner2@test.com",
  "RoleName": "Owner"
}

###
