@Restaurants.API_HostAddress = https://localhost:7112
@token = CfDJ8MsiFju5D8dEhQLF9cu1mcomI_Wl2BNAKVy9lTLKabQwjV49XJ6ZH8tP43c85XpBQAQrgqY1qLnJ2i039fnwL8xO47ucY1mj1zoDr1zdF7HprAqqRu4-NfA1Vahmt8aH8XSLdasgSvPzUv8-12ezZlc69xVEnSEutlW5W9VUSYfRPXNa_3vOxzKy7KtE3tb1BvoBGA3oiaVAlrz8ISL-iYA0ueJ4g8kphITqBoc1E4k3zXmq3S_3Ib91TNqebc4dbvKy1-gpokN2TuNPJ88nO9lc32x5ZrpKvfewmivSqKbUdQwUOd7zOU3wodsFzNioIPBZqp5WKDAj3Hwp8R1nZbE07lHJ-D4O7gGlOffcGBjYJND0qAPrFvWWkEIpJbwsTCE4V1cj8LRRuSlrZi2Xbaw0pseBXogHuJHRT_HhreKx9qXIAB5eqeE4A0BLnt7KqvwcoV29_LuFwRPdDvw6ezM9MLHxQeL1CRXniD7f6338NeYAp5emcqLlzQJKXs0tIQ4ItTqJ2kLIafFw3hWqp83QUoNmVw-jkM-Ht_G6dfWfFPx6cXhtosrFzVV6BFsQH_Mqg80eCrzbFlpMYto5k8hzO45BJ0XEpfYoSH6srnbJ9x4ImHKqg-uCZNaPeq3EtwDdn-KGx3BE2nihS_ATg9XPApHIh4Yk2DUv4C7-u9y-VMXRsGU6yYdiYMsQP5-1tN5UiSAtFrasha7k54xr_6xt1oyfsTELpQwH8q_fTuUeBjGmEs7Q15aMUIZYZi8MxaMlyy3m9Zsb6zoyB_2CUSEINZFIfG5VBTBw-E7UAECK7_lly706vMAt7RDC_3a5tW4do0kRkX9aU6lSTxOk5snvQg7rzO_x4dDWw5sKkgYPuv_1DOlUVv4DIVRdcTcKEA

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
#Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurants/16
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Pukka Pizzas",
  "Description": "Funky Pizzas",
  "Category": "Italian",
  "ContactEmail": "info@funkypizzas.com",
  "ContactNumber": "04745 445 4",
  "PostalCode":"12457-444",
  "City": "Paris",
  "Street": "Rue de la Paix",
  "HasDelivery": true
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/16
Authorization: Bearer {{token}}
###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/16
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "Name": "Pukka Pizza",
  "Description": "funky pizza restaurant",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes
Content-Type: application/json

{
 "Name": "Chicken Biriyani",
 "Description": "A delicious dish made with basmati rice, chicken and a variety of spices",
 "Price": 13.50,
 "KiloCalories": 850
}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes
Authorization: Bearer {{token}}
###

GET {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes/18
Authorization: Bearer {{token}}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/4/dishes
Authorization: Bearer {{token}}
###
POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "christopher.stubbs@transparity.com",
  "password": "Password1!"
}

###
POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@test.com",
  "password": "Password1!"
}
###
PATCH {{Restaurants.API_HostAddress}}/api/identity/user
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "DateOfBirth": "2010-01-01",
  "Nationality": "British"
}

###
